// models/ListingModel.js
// This file defines the structure for car listings in Firestore

/**
 * Firestore Schema for a car listing
 * Collection: 'listings'
 * 
 * @typedef {Object} Listing
 * @property {string} id - Document ID (auto-generated by Firestore)
 * @property {string} brand - Car brand (e.g., BMW, Audi, Toyota)
 * @property {string} model - Car model (e.g., 3 Series, A4, Corolla)
 * @property {number} year - Year of manufacture
 * @property {number} price - Price in PLN
 * @property {number} mileage - Mileage in kilometers
 * @property {string} fuelType - Type of fuel (e.g., Benzyna, Diesel, Elektryczny)
 * @property {string} transmission - Transmission type (e.g., Manualna, Automatyczna)
 * @property {number} engineCapacity - Engine size in cubic centimeters (cm³)
 * @property {number} power - Engine power in horsepower (KM)
 * @property {number} visualCondition - Visual condition rating (1-5)
 * @property {string} description - Detailed description of the car
 * @property {string[]} imageUrls - Array of image URLs
 * @property {string} mainImageUrl - URL of the main image to display
 * @property {FirebaseFirestore.Timestamp} createdAt - Creation timestamp
 * @property {FirebaseFirestore.Timestamp} updatedAt - Last update timestamp
 * @property {string} userId - ID of the user who created the listing
 * @property {number} views - Number of views for this listing
 * @property {string} bodyType - Type of car body (e.g., SUV, Sedan, Kombi)
 * @property {string[]} features - Array of car features/equipment
 * @property {boolean} warranty - Whether the car has a warranty
 * @property {FirebaseFirestore.Timestamp} warrantyUntil - Warranty expiration date
 * @property {FirebaseFirestore.Timestamp} inspectionValidUntil - Technical inspection validity date
 * @property {boolean} firstOwner - Whether the seller is the first owner
 * @property {boolean} serviceHistory - Whether the car has service history
 * @property {boolean} extraTires - Whether the car comes with extra tires
 * @property {string} sellerPhone - Seller's phone number
 * @property {string} sellerEmail - Seller's email address
 * @property {string} location - The location where the car is available
 */

/**
 * Create a new listing document to be stored in Firestore
 * @param {Object} data - The listing data
 * @returns {Object} - Formatted listing object
 */
const createListing = (data) => {
    // Default values that apply if not provided
    const timestamp = admin.firestore.FieldValue.serverTimestamp();
    
    return {
      brand: data.brand,
      model: data.model,
      year: data.year,
      price: data.price,
      mileage: data.mileage || 0,
      fuelType: data.fuelType || null,
      transmission: data.transmission || null,
      engineCapacity: data.engineCapacity || null,
      power: data.power || null,
      visualCondition: data.visualCondition || 3, // Default middle rating
      description: data.description || '',
      imageUrls: data.imageUrls || [],
      mainImageUrl: data.mainImageUrl || (data.imageUrls && data.imageUrls.length > 0 ? data.imageUrls[0] : null),
      createdAt: timestamp,
      updatedAt: timestamp,
      userId: data.userId,
      views: 0,
      bodyType: data.bodyType || null,
      features: data.features || [],
      warranty: data.warranty || false,
      warrantyUntil: data.warrantyUntil || null,
      inspectionValidUntil: data.inspectionValidUntil || null,
      firstOwner: data.firstOwner || false,
      serviceHistory: data.serviceHistory || false,
      extraTires: data.extraTires || false,
      sellerPhone: data.sellerPhone || null,
      sellerEmail: data.sellerEmail || null,
      location: data.location || null
    };
  };
  
  /**
   * Update a listing document
   * @param {Object} data - The listing update data
   * @returns {Object} - Formatted update object
   */
  const updateListing = (data) => {
    const updates = { ...data };
    
    // Always update the timestamp
    updates.updatedAt = admin.firestore.FieldValue.serverTimestamp();
    
    // Remove fields that shouldn't be updated
    delete updates.id;
    delete updates.userId;
    delete updates.createdAt;
    delete updates.views; // Views should be incremented with a separate function
    
    return updates;
  };
  
  /**
   * Increment the view count for a listing
   * @param {string} listingId - The ID of the listing
   * @returns {Promise<void>}
   */
  const incrementViews = async (listingId) => {
    const listingRef = db.collection('listings').doc(listingId);
    
    await listingRef.update({
      views: admin.firestore.FieldValue.increment(1)
    });
  };
  
  module.exports = {
    createListing,
    updateListing,
    incrementViews
  };
  
  
  // models/UserModel.js
  // This file defines the structure for user data in Firestore
  
  /**
   * Firestore Schema for a user
   * Collection: 'users'
   * 
   * @typedef {Object} User
   * @property {string} uid - Firebase Auth user ID (used as document ID)
   * @property {string} email - User's email address
   * @property {string} displayName - User's display name
   * @property {string} phoneNumber - User's phone number
   * @property {string} photoURL - URL to user's profile picture
   * @property {FirebaseFirestore.Timestamp} createdAt - Account creation timestamp
   * @property {FirebaseFirestore.Timestamp} updatedAt - Last update timestamp
   * @property {boolean} isDealer - Whether the user is a car dealer
   * @property {string} dealerName - Name of dealership (if dealer)
   * @property {string} dealerAddress - Address of dealership (if dealer)
   * @property {string} dealerNIP - NIP number (tax ID) for dealers
   */
  
  /**
   * Create a new user document to be stored in Firestore
   * @param {Object} data - The user data
   * @returns {Object} - Formatted user object
   */
  const createUser = (data) => {
    const timestamp = admin.firestore.FieldValue.serverTimestamp();
    
    return {
      uid: data.uid,
      email: data.email,
      displayName: data.displayName || null,
      phoneNumber: data.phoneNumber || null,
      photoURL: data.photoURL || null,
      createdAt: timestamp,
      updatedAt: timestamp,
      isDealer: data.isDealer || false,
      dealerName: data.dealerName || null,
      dealerAddress: data.dealerAddress || null,
      dealerNIP: data.dealerNIP || null
    };
  };
  
  /**
   * Update a user document
   * @param {Object} data - The user update data
   * @returns {Object} - Formatted update object
   */
  const updateUser = (data) => {
    const updates = { ...data };
    
    // Always update the timestamp
    updates.updatedAt = admin.firestore.FieldValue.serverTimestamp();
    
    // Remove fields that shouldn't be updated
    delete updates.uid;
    delete updates.email; // Email should be updated through Firebase Auth
    delete updates.createdAt;
    
    return updates;
  };
  
  module.exports = {
    createUser,
    updateUser
  };